jwt:
  secret: &jwt-secret 81655831894877659963357094989595
  key-id: my-key-id

spring:
  application:
    name: streamer-api
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2.console.enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          secret: *jwt-secret

bypass:
  urls:
    - /auth/**
    - /actuator/**

oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID}


management:
  endpoints:
    web:
      exposure:
        include: health

aws:
  s3:
    access-key: ${S3_BUCKET_ACCESS_KEY}
    secret-key: ${S3_BUCKET_SECRET_KEY}
    region: ${S3_BUCKET_REGION}
    bucket-name: ${S3_BUCKET_NAME}
