spring:
  application:
    name: stramer-api
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2.console.enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health

aws:
  s3:
    access-key: ${S3_BUCKET_ACCESS_KEY}
    secret-key: ${S3_BUCKET_SECRET_KEY}
    region: ${S3_BUCKET_REGION}
    bucket-name: ${S3_BUCKET_NAME}
